### ISSUE TITLE
storybook-addon-swc@1.2 requires package extensions with Yarn 3

### ISSUE THREAD

**Issue by wegry** [Karibash/storybook-addon-swc#51]
Updating to `storybook-addon-swc@1.2` requires the following `packageExtensions` with `yarn@3.5` and PnP enabled.

```yaml
packageExtensions:
  storybook-addon-swc@^1.2:
    dependencies:
      terser-webpack-plugin: ^5.2.5
  terser-webpack-plugin@^5.2.5:
    dependencies:
      "@swc/core": '*' # there might be a better version to pin to?
```

`terser-webpack-plugin` should be specified in a way that yarn pulls it in.
